#!/usr/bin/env bash
#Configure your Nginx server

ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=muFd_NzAWCI&t=29s permanent;"

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
sed -i '30i $ADD301_REDIRECT' etc/nginx/sites-available/default
service nginx restart
